### ISSUE TITLE
snap "bcompare" has no plug named "removable-media"

### ISSUE THREAD

**Issue by jrussell88** [mmtrt/bcompare#1]
I'm filing this on GitHub as there are no contact details under 'snap info bcompare'.

The snap lacks a plug for removable-media which means the application cannot access folders under /media and /mnt.

Can you add this plug? Thanks.

**Comment by mmtrt** [comment]
released the update so snap now includes removable-media.

To update manually usually it should be auto updated if not then run below command.

`snap refresh bcompare`
